

export { default as ExperienceAndEducation} from './ExperienceAndEducation'
export { default as Hero} from './hero'
export { default as Services } from './services'
export { default as Banner} from './banner'
export { default as ContactAction } from './contactAction'
export { default as Navbar } from './navbar'
export { default as Footer} from './footer'
export { default as Feedbacks} from './feedbacks'
export { default as Gallery} from './gallery'
export { default as Posts} from './posts'
export { default as Projects} from './projects'
export { default as Skills} from './skills'
export { default as LatestBlog} from './LatestBlog'
export { default as LatestProject} from './LatestProject'
export { default as Contact} from './contact'
